# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'guardian' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for guardian
  pod 'GRDB.swift/SQLCipher'
  pod 'RxGRDB/SQLCipher'
  pod 'SQLCipher', '~> 4.0'
  pod 'Moya/RxSwift', :git => 'https://github.com/sachin-rao-coditas/Moya.git'
  pod 'RxSwift', '~> 6.2.0'
  pod 'RxCocoa', '~> 6.2.0'
  pod 'Kingfisher'
  pod 'SnapKit', '~> 5.0.0'
  pod 'ProgressWebViewController'

end
